# Generated by Django 4.2.16 on 2026-04-16 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("open_room", "Mở phòng"),
                            ("add_service", "Thêm dịch vụ"),
                            ("stop_service", "Dừng dịch vụ"),
                            ("add_food", "Gọi đồ ăn/uống"),
                            ("add_outside", "Thêm mua ngoài"),
                            ("remove_item", "Xóa món"),
                            ("merge_table", "Gộp bàn"),
                            ("unmerge_table", "Hủy gộp bàn"),
                            ("checkout", "Thanh toán"),
                            ("delete_revenue", "Xóa doanh thu"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="core.roomsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
